version: '3.8'

services:
  npm-manage-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: npm-manage-mcp
    environment:
      NODE_ENV: production
      # Add any other environment variables
    volumes:
      # Mount host directory for package operations
      - ./workspace:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge