version: '3.8'

services:
  mcp-env-manager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-env-manager
    environment:
      - NODE_ENV=production
      - MCP_ENV_ENCRYPTION_KEY=${MCP_ENV_ENCRYPTION_KEY}
    volumes:
      - mcp_env_data:/data
    ports:
      - "3000:3000"
    restart: unless-stopped
    command: node dist/bin/mcp-env-manager.js --sse --port 3000

volumes:
  mcp_env_data:
    name: mcp_env_data 
