version: '3.8'

services:
  lulu-print-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lulu-print-mcp
    environment:
      - LULU_CLIENT_KEY=${LULU_CLIENT_KEY}
      - LULU_CLIENT_SECRET=${LULU_CLIENT_SECRET}
      - LULU_USE_SANDBOX=${LULU_USE_SANDBOX:-false}
      - DEBUG=${DEBUG:-false}
      - NODE_ENV=production
    volumes:
      - ./logs:/app/logs
    networks:
      - lulu-network
    restart: unless-stopped

networks:
  lulu-network:
    driver: bridge